version: "3.0"

services:
  pg: 
    image: postgres:alpine3.16
    container_name: pg_database
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: bac_database
    volumes: 
      - ./_postgres:/var/lib/postgresql/data
      - ./database:/files 